In [9]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    '''
    without using container
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()
    '''
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    '''
    without using container
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    '''
    out = self.network(features)
    return out

In [10]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.6245],
        [0.6341],
        [0.6262],
        [0.6316],
        [0.6229],
        [0.6272],
        [0.6281],
        [0.6279],
        [0.6236],
        [0.6374]], grad_fn=<SigmoidBackward0>)

In [12]:
# show model weights
model.network[0].weight

Parameter containing:
tensor([[-0.1648, -0.0711, -0.0778, -0.3215,  0.2679],
        [ 0.3129,  0.3082,  0.1547, -0.2685, -0.0106],
        [ 0.2562,  0.2728, -0.1447,  0.3031,  0.0325]], requires_grad=True)

In [13]:
# show model weights
model.network[2].weight

Parameter containing:
tensor([[-0.1984,  0.1949, -0.0689]], requires_grad=True)

In [7]:
!pip install torchinfo

In [8]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00