In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
torch.cuda.is_available()

True

In [3]:
device = torch.device('cuda')

In [4]:
# Creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.0883, 0.8791, 0.5191],
        [0.5723, 0.8420, 0.7677]], device='cuda:0')

In [5]:
a = torch.rand((2,3))
a

tensor([[0.8663, 0.6240, 0.7138],
        [0.5598, 0.9574, 0.0029]])

In [6]:
# moving an existing tensor to GPU
b = a.to(device)

In [7]:
b + 5

tensor([[5.8663, 5.6240, 5.7138],
        [5.5598, 5.9574, 5.0029]], device='cuda:0')

**Comparing tensors on CPU vs GPU**

In [8]:
import torch
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# Measure time on GPu
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 28.0646 seconds
Time on GPU: 0.6897 seconds

Speedup (CPU time / GPU time): 40.69243177075069


**Reshaping Tensors**

In [9]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [11]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
b = torch.rand(2,3,4)
b

tensor([[[0.5678, 0.8943, 0.0207, 0.0445],
         [0.5224, 0.8011, 0.3960, 0.6238],
         [0.7466, 0.4407, 0.5704, 0.0565]],

        [[0.6286, 0.5080, 0.7146, 0.8351],
         [0.7664, 0.2038, 0.6463, 0.5282],
         [0.4659, 0.9405, 0.7997, 0.9476]]])

In [13]:
# permute(new technique)
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [14]:
# unsqueeze
# image size
c = torch.rand(226, 226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [15]:
# sequeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

**NumPy and PyTorch**

In [16]:
import numpy as np

In [17]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [18]:
b = a.numpy()

In [19]:
b

array([1, 2, 3])

In [20]:
type(b)

numpy.ndarray

In [21]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [22]:
torch.from_numpy(c)

tensor([1, 2, 3])