In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Usinf GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


Creating Tensors in Pytorch

In [3]:
#using empty
torch.empty(2,3)

tensor([[4.1930e-12, 4.4158e-41, 4.1930e-12],
        [4.4158e-41, 4.1931e-12, 4.4158e-41]])

In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.8030, 0.1079, 0.9977],
        [0.7249, 0.3754, 0.5976]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.8280, 0.8814, 0.2870],
        [0.0147, 0.9446, 0.1851]])

In [10]:
# manual_seed
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [11]:
# manual_seed
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

#using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[135348132691328, 135348132691328,               0],
        [              0,               0,               0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
#torch.rand_like(x)# because x having integers values and rand function genrates a float values between 0 - 1.

In [20]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

Tenssor Data Types

In [21]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
# fing data type
x.dtype

torch.int64

In [23]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
# using to()
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical operations

1. Scalar Operation

In [27]:
x = torch.rand(2,2)
x

tensor([[0.7041, 0.5573],
        [0.6959, 0.9849]])

In [28]:
# addition
a = x + 2
# substraction
b = x - 2
# multiplication
c= x * 3
# division
d = x / 3
# int division
e = (x * 100)//3
# mod
f = ((x * 100)//3)%2
# power
g = x**2
print(a,b,c,d,e,f,g, sep="\n")

tensor([[2.7041, 2.5573],
        [2.6959, 2.9849]])
tensor([[-1.2959, -1.4427],
        [-1.3041, -1.0151]])
tensor([[2.1123, 1.6718],
        [2.0876, 2.9548]])
tensor([[0.2347, 0.1858],
        [0.2320, 0.3283]])
tensor([[23., 18.],
        [23., 32.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0.4957, 0.3105],
        [0.4842, 0.9701]])


2. Ement wise Operations

In [29]:
x = torch.rand(2,3)
y = torch.rand(2,3)

print(x,y, sep="\n")

tensor([[0.2924, 0.4823, 0.6150],
        [0.4967, 0.4521, 0.0575]])
tensor([[0.0687, 0.0501, 0.0108],
        [0.0343, 0.1212, 0.0490]])


In [30]:
# add
aa = x + y
# sub
bb = x - y
# multiply
cc = x * y
# division
dd = x / y
# power
ff = a ** b
# mod
gg = a % b
print(aa,bb,cc,dd,ff,gg, sep="\n")

tensor([[0.3611, 0.5324, 0.6257],
        [0.5311, 0.5733, 0.1065]])
tensor([[0.2237, 0.4323, 0.6042],
        [0.4624, 0.3309, 0.0085]])
tensor([[0.0201, 0.0242, 0.0066],
        [0.0171, 0.0548, 0.0028]])
tensor([[ 4.2560,  9.6331, 57.1744],
        [14.4714,  3.7297,  1.1731]])
tensor([[0.2755, 0.2580],
        [0.2744, 0.3295]])
tensor([[-1.1836, -0.3282],
        [-1.2166, -0.0603]])


In [31]:
c = torch.tensor([1, -2, 3, -4])


In [32]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [33]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [34]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [35]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [36]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [37]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [38]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction Operation

In [39]:
e = torch.randint(size=(2,3), low=0, high = 10, dtype=torch.float32)
e

tensor([[9., 4., 4.],
        [5., 4., 0.]])

In [40]:
# sum
aaa = torch.sum(e)
# sum along columns
bbb = torch.sum(e, dim=0)
# sum along rows
ccc = torch.sum(e, dim=1)
print(aaa,bbb,ccc, sep="\n")

tensor(26.)
tensor([14.,  8.,  4.])
tensor([17.,  9.])


In [41]:
# mean
eee = torch.mean(e)
# mean along columns
fff = torch.mean(e, dim=0)
print(eee,fff, sep="\n")

tensor(4.3333)
tensor([7., 4., 2.])


In [42]:
# median
torch.median(e)

tensor(4.)

In [43]:
# max and min
hhh = torch.max(e)
iii = torch.min(e)
print(hhh,iii, sep="\n")

tensor(9.)
tensor(0.)


In [44]:
# product
torch.prod(e)

tensor(0.)

In [45]:
# standard deviation
torch.std(e)

tensor(2.8752)

In [46]:
# variance
torch.var(e)

tensor(8.2667)

In [47]:
# argmax
torch.argmax(e)

tensor(0)

In [48]:
# argmin
torch.argmin(e)

tensor(5)

4. Matrix Operations

In [49]:
f = torch.randint(size=(2,3), low =0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 9, 3],
        [0, 9, 3]])
tensor([[7, 9],
        [5, 2],
        [9, 6]])


In [50]:
# matrix multiplication
torch.matmul(f, g)

tensor([[128, 108],
        [ 72,  36]])

In [51]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [52]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [9, 9],
        [3, 3]])

In [53]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 2., 8.],
        [9., 6., 9.],
        [1., 9., 2.]])

In [54]:
# determinant
torch.det(h)

tensor(168.0000)

In [55]:
# inverse
torch.inverse(h)

tensor([[-0.4107,  0.4048, -0.1786],
        [-0.0536,  0.0238,  0.1071],
        [ 0.4464, -0.3095,  0.1071]])

5. Comparison Operations

In [56]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 2, 9],
        [7, 2, 9]])
tensor([[4, 4, 9],
        [4, 4, 8]])


In [57]:
# greater than
i > j

tensor([[False, False, False],
        [ True, False,  True]])

In [58]:
# less than
i < j

tensor([[ True,  True, False],
        [False,  True, False]])

In [59]:
# equal to
i == j

tensor([[False, False,  True],
        [False, False, False]])

6. Special Functions

In [60]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 1., 8.],
        [2., 6., 1.]])

In [61]:
# log
torch.log(k)

tensor([[1.0986, 0.0000, 2.0794],
        [0.6931, 1.7918, 0.0000]])

In [62]:
# exp
torch.exp(k)

tensor([[2.0086e+01, 2.7183e+00, 2.9810e+03],
        [7.3891e+00, 4.0343e+02, 2.7183e+00]])

In [63]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.0000, 2.8284],
        [1.4142, 2.4495, 1.0000]])

In [64]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.7311, 0.9997],
        [0.8808, 0.9975, 0.7311]])

In [65]:
# softmax
torch.softmax(k, dim=0)

tensor([[7.3106e-01, 6.6929e-03, 9.9909e-01],
        [2.6894e-01, 9.9331e-01, 9.1105e-04]])

In [66]:
# relu
torch.relu(k)

tensor([[3., 1., 8.],
        [2., 6., 1.]])

Inplace Operations

In [67]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6750, 0.1424, 0.3790],
        [0.0055, 0.6368, 0.3295]])
tensor([[0.2203, 0.1821, 0.3241],
        [0.7375, 0.5283, 0.9306]])


In [68]:
m.add_(n)

tensor([[0.8953, 0.3245, 0.7031],
        [0.7429, 1.1651, 1.2601]])

In [69]:
m

tensor([[0.8953, 0.3245, 0.7031],
        [0.7429, 1.1651, 1.2601]])

In [70]:
n

tensor([[0.2203, 0.1821, 0.3241],
        [0.7375, 0.5283, 0.9306]])

In [71]:
m.relu_()

tensor([[0.8953, 0.3245, 0.7031],
        [0.7429, 1.1651, 1.2601]])

In [72]:
m

tensor([[0.8953, 0.3245, 0.7031],
        [0.7429, 1.1651, 1.2601]])

Copying a Tensor

In [73]:
 s = torch.rand(2,3)
 s

tensor([[0.3213, 0.3537, 0.9894],
        [0.0231, 0.3032, 0.1898]])

In [74]:
r = s

In [75]:
r

tensor([[0.3213, 0.3537, 0.9894],
        [0.0231, 0.3032, 0.1898]])

In [76]:
s[0][0] = 0

In [77]:
s

tensor([[0.0000, 0.3537, 0.9894],
        [0.0231, 0.3032, 0.1898]])

In [78]:
r

tensor([[0.0000, 0.3537, 0.9894],
        [0.0231, 0.3032, 0.1898]])

In [79]:
id(s)

135343757673488

In [80]:
id(r) # both the variables has a same location in memory

135343757673488

In [81]:
# This is the right way to make copy
r = s.clone()

In [82]:
s

tensor([[0.0000, 0.3537, 0.9894],
        [0.0231, 0.3032, 0.1898]])

In [83]:
r

tensor([[0.0000, 0.3537, 0.9894],
        [0.0231, 0.3032, 0.1898]])

In [84]:
s[0][0] = 10

In [85]:
s

tensor([[10.0000,  0.3537,  0.9894],
        [ 0.0231,  0.3032,  0.1898]])

In [86]:
r

tensor([[0.0000, 0.3537, 0.9894],
        [0.0231, 0.3032, 0.1898]])

In [87]:
id(s)

135343757673488

In [88]:
id(r)

135343757681088